events: {
  shape: sql_table
  id: "String (Event ID)"
  name: "String"
  description: "String"
  start_time: "Timestamp"
  end_time: "Timestamp"
  available_tickets: "Number"
  total_tickets: "Number"
  price: "Number"
}

tickets: {
  shape: sql_table
  id: "String (Ticket ID)"
  event_id: "Reference to Event"
  status: "Enum (Available, Sold, Onhold)"
}

users: {
  shape: sql_table
  id: "String (User ID)"
  name: "String"
  email: "String"
}

purchases: {
  shape: sql_table
  id: "String (Purchase ID)"
  user_id: "Reference to User"
  event_id: "Reference to Event"
  ticket_id: "Reference to Ticket"
  purchase_status: "Enum (Active, Cancelled)"
  purchase_time: "Timestamp"
}

events -> tickets: "Has Many"
users -> purchases: "Has Many"
tickets -> purchases: "Has Many"
events -> purchases: "Has Many"
